mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
proxies:
- name: Singapore 1
  type: vmess
  server: sg-1.stunnel.cc
  port: 8443
  uuid: 34382039-3920-4937-a035-362035342039
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /ws
    headers:
      Host: sg-1.stunnel.cc
  tls: true
  skip-cert-verify: true
proxy-groups:
- name: All-In-One-Group
  type: select
  proxies:
  - Singapore 1
  - DIRECT
rules:
- MATCH,All-In-One-Group
