mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
proxies:
- name: Singapore 1
  type: vmess
  server: sg5.vpnjantit.com
  port: 10001
  uuid: e4139578-7884-11f1-9bb1-0b851906dfd2
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
  tls: true
  skip-cert-verify: true
  sni: ''
- name: Singapore 2
  type: vmess
  server: sg5.vpnjantit.com
  port: 10001
  uuid: e4139578-7884-11f1-9bb1-0b851906dfd2
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
  tls: true
  skip-cert-verify: true
- name: Singapore 3
  type: vmess
  server: sg5.vpnjantit.com
  port: 10001
  uuid: e4139578-7884-11f1-9bb1-0b851906dfd2
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
  tls: true
  skip-cert-verify: true
- name: Singapore 4
  type: vmess
  server: sg5.vpnjantit.com
  port: 10001
  uuid: e4139578-7884-11f1-9bb1-0b851906dfd2
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
    headers:
      Host: telegram.org
  tls: true
  skip-cert-verify: true
  sni: telegram.org
proxy-groups:
- name: All-In-One-Group
  type: select
  proxies:
  - Singapore 1
  - Singapore 2
  - Singapore 3
  - Singapore 4
  - DIRECT
rules:
- MATCH,All-In-One-Group
